services:
  webrtc-stream:
    build: .
    container_name: live-cam
    restart: unless-stopped
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - PYTHONUNBUFFERED=1
