services:
  webrtc-stream:
    build: .
    container_name: live-cam
    restart: unless-stopped
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - /srv/webcam/sqlite:/app/data
    environment:
      - PYTHONUNBUFFERED=1 
      # ==================================
      # OPÇÃO 1: CONFIGURAÇÃO PARA MYSQL =
      # ==================================
      # - DB_TYPE=mysql
      # - DB_HOST=db
      # - DB_USER=stream_user
      # - DB_PASS=stream_pass
      # - DB_NAME=stream_db
      # ==========================================
      # OPÇÃO 2: CONFIGURAÇÃO PARA SQLITE
      # (Para usar, comente a Opção 1 e descomente abaixo)
      # ==========================================
      - DB_TYPE=sqlite
      - DB_NAME=/app/data/stream.db
      
    # Se for usar SQLite, você pode comentar as duas linhas abaixo e o serviço 'db' inteiro
    # depends_on:
    #   - db

  # Serviço do MySQL (Só é necessário se DB_TYPE=mysql)
  db:
    image: mysql:latest
    container_name: stream-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: stream_db
      MYSQL_USER: stream_user
      MYSQL_PASSWORD: stream_pass
    ports:
      - "3306:3306"
    volumes:
      - /srv/webcam/nysql:/var/lib/mysql
  
  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    container_name: adminer
    ports:
      - "8081:8080"
    volumes:
      - /srv/webcam/sqlite:/data